// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChAulGpiXsPmIACunp6zSxzfWKT6NXYZA',
    appId: '1:437857248799:web:fd9f3ee6010b161931572a',
    messagingSenderId: '437857248799',
    projectId: 'soil-monitoring-a2675',
    authDomain: 'soil-monitoring-a2675.firebaseapp.com',
    databaseURL: 'https://soil-monitoring-a2675-default-rtdb.firebaseio.com',
    storageBucket: 'soil-monitoring-a2675.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAulGpiXsPmIACunp6zSxzfWKT6NXYZA',
    appId: '1:437857248799:web:fd9f3ee6010b161931572a',
    messagingSenderId: '437857248799',
    projectId: 'soil-monitoring-a2675',
    authDomain: 'soil-monitoring-a2675.firebaseapp.com',
    databaseURL: 'https://soil-monitoring-a2675-default-rtdb.firebaseio.com',
    storageBucket: 'soil-monitoring-a2675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:your-project-number:ios:your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'soil-monitoring-a2675',
    authDomain: 'soil-monitoring-a2675.firebaseapp.com',
    databaseURL: 'https://soil-monitoring-a2675-default-rtdb.firebaseio.com',
    storageBucket: 'soil-monitoring-a2675.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:your-project-number:macos:your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'soil-monitoring-a2675',
    authDomain: 'soil-monitoring-a2675.firebaseapp.com',
    databaseURL: 'https://soil-monitoring-a2675-default-rtdb.firebaseio.com',
    storageBucket: 'soil-monitoring-a2675.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:your-project-number:windows:your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'soil-monitoring-a2675',
    authDomain: 'soil-monitoring-a2675.firebaseapp.com',
    databaseURL: 'https://soil-monitoring-a2675-default-rtdb.firebaseio.com',
    storageBucket: 'soil-monitoring-a2675.appspot.com',
  );
}
